### ISSUE TITLE
`queenbee pollination workflows list` returns an error when there is no workflow

### ISSUE THREAD

**Issue by mostaphaRoudsari** [pollination/queenbee-pollination#1]
Probably it is only an extra check to handle empty lists.

**Comment by mostaphaRoudsari** [comment]
This is correct for all the list commands.

@AntoineDao, any idea why this is happening? It is shared between different micro-services.

**Comment by AntoineDao** [comment]
I'm thinking/hoping it's an issue with the CLI implementation rather than the servers. What does the error look like?

**Comment by mostaphaRoudsari** [comment]
I did try to handle it from CLI as I was hoping the same but it fails in the call to get the list. I assume it happens during the deserialization of content from database.

**Comment by AntoineDao** [comment]
Are you getting an "internal server error" message? Mind printing the message you get here?

**Comment by mostaphaRoudsari** [comment]
Yes. It was an internal server error. 

Now that I have some artifacts I can't recreate the error anymore! I can delete them and try to generate the error but it is nothing informative. It just says internal server error.

**Comment by mostaphaRoudsari** [comment]
Actually I have the screenshot for you. See here: https://github.com/pollination/artifact-service/issues/1

**Comment by AntoineDao** [comment]
I think this is now fixed so closing. Feel free to reopen if similar issue happens again.
