### ISSUE TITLE
Add support for partial UUID

### ISSUE THREAD

**Issue by mostaphaRoudsari** [pollination/queenbee-pollination#3]
I found this feature very nice in docker CLI that you can pass only part of the UUID to the command instead of the full id. This is not critical but very nice to have IMO.

**Comment by AntoineDao** [comment]
Would it be better if you could reference it by name instead of full or partial uuid?

**Comment by mostaphaRoudsari** [comment]
We are currently allowing workflows with the same name. If we enforce unique names then supporting names might be the better option

**Comment by AntoineDao** [comment]
I think enforcing a unique "<owner>/<workflow_name>" the same way github and docker does will lead to a slightly easier to use system for users who won't have to track ids.

**Comment by AntoineDao** [comment]
I am going to close this as we are now using namespaced names to identify workflows (ie: `antoinedao/daylight-factor` instead of a long uuid string).

Feel free to re-open if you still think this needs addressing.
