### ISSUE TITLE
How to overwrite input values for a workflow?

### ISSUE THREAD

**Issue by mostaphaRoudsari** [pollination/queenbee-pollination#6]
@AntoineDao, do we have a strategy in place for passing input values to a workflow. I know you can do it under the hood when submit a workflow in Argo but how do we handle that from Pollination side? Do we expect the workflow to already include all the inputs before sent to Pollination? Is that what `hydrate` is designed to do?

Should we consider to pass input values to a workflow when `submit` a workflow to Pollination?

**Comment by AntoineDao** [comment]
Currently the simulation API endpoint requires a `workflow` and `inputs` in the payload used to `submit` a new simulation.

These are then (in theory) merged into the top levels inputs of the workflow template, converted to Argo and submitted.

![image](https://user-images.githubusercontent.com/20436635/71638915-6d71ca80-2cb8-11ea-994e-9bf7915416cd.png)

Does this answer your question or have I misunderstood you?

PS: on github at 11pm on the 31st of December... really? :policeman:

**Comment by mostaphaRoudsari** [comment]
Nice! I should have checked the end-points. That means that we can extend the CLI to handle it.

PS: I took a short break to ask this one before I forget 😁
